### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by AFCMS** [Noodlemire/projectile#1]
Log:
`AsyncErr: ServerThread::run Lua: Runtime error from mod 'projectile' in callback luaentity_Step(): ...ods\minetest-5.3.0-win64\bin\..\mods\projectile\init.lua:421: attempt to index global 'node_damage' (a nil value)
stack traceback:
	...ods\minetest-5.3.0-win64\bin\..\mods\projectile\init.lua:421: in function 'on_impact'
	...mods\minetest-5.3.0-win64\bin\..\mods\projectile/api.lua:245: in function <...mods\minetest-5.3.0-win64\bin\..\mods\projectile/api.lua:200>`

**Comment by Noodlemire** [comment]
Fixed with update 1.1.3
